### ISSUE TITLE
My cards not recognized

### ISSUE THREAD

**Issue by SebastianBO** [dickreuter/Poker#100]
No DPI scaling, been testing literally everything. Spent a couple of hours doing the new table setup without success. It can't possibly be only me who has this problem? 

1. Table not recognized in the GUI error
2. Terminal error output log "INFO - My cards: []
WARNING - My cards not recognized"
3. How do I stop the bot, with what keybind? Or do I always have to facepalm my face into the keyboard

**Comment by SebastianBO** [comment]
I appreciate everything you've done. If I could donate I would

**Comment by dickreuter** [comment]
Haha. What table are you using and can you attach a screenshot from the log
folder. Did you mark the cards area correctly?

**Comment by rokken1337** [comment]
Same here. I just figured out that my dark desktop background caused the problem.

**Comment by SebastianBO** [comment]
I see, and what did you change it too? :)

**Comment by rokken1337** [comment]
I've changed it to the blue default Win10 background.

**Comment by SebastianBO** [comment]
Never felt this stupid in my life, making apps/games/taxes is easier than this for me. I can't even get your default "PartyPoker 6" to work, "My cards not recognized still".

**Comment by dickreuter** [comment]
Are you using the correct table scraper? Currently only PartyPoker 6 Players Fast Forward $1-$2 NL Hold'em works

**Comment by amauryleproux** [comment]
same for me, I've got no idea how to make it works, the mouse is searching and I struggle to close everything
