### ISSUE TITLE
Database Offline?

### ISSUE THREAD

**Issue by BigWinston** [dickreuter/Poker#104]
Hey,

Am trying to connect to the database using the connection string.  It keeps timing out - is it offline?
`mongodb://neuron_poker:donald@dickreuter.com/neuron_poker`

I have also tried a simple script to ping for it and this fails too saying the connection was actively refused:
```
connectionString = f'mongodb://neuron_poker:donald@dickreuter.com/neuron_poker'
client = MongoClient(connectionString, 27017)
res = client.db_name.command('ping')
print(res)
```

As a 3rd test, I have tried testing the connection with MongoDB Compass.  Same result.

Thanks,

BW

**Comment by murrayeinstein** [comment]
Hi, 

Having the exact same problem. Tried checking the server was online a few times but this issue was already flagged. Apparently fixed February 2019? 

Thanks,

Young Albert

**Comment by dickreuter** [comment]
Restarted server.

**Comment by andno037** [comment]
Looks like it's offline again :)

**Comment by As-Tomas** [comment]
Happy new years

2020-12-31, kt 22:42, andno037 <notifications@github.com> rašė:

**Comment by K1utzer** [comment]
I think it's offline again
