### ISSUE TITLE
Looking for someone to build a poker app for me

### ISSUE THREAD

**Issue by asayagtal** [dickreuter/Poker#110]
Something like Zynga poker with some extra features.
Anyone can handle building this kind of app? 
Thanks in advance,
Tal.

Asayagtal@gmail.com

**Comment by dickreuter** [comment]
Yes happy to do it. But not going to be cheap. How much can you invest?

**Comment by asayagtal** [comment]
Thanks for your answer.
I have the money, but im not willing to pay huge amounts unless its justifies it.
Whats your predicted range?

**Comment by dickreuter** [comment]
$100k for an initial version.
