### ISSUE TITLE
Cards Not Recognised

### ISSUE THREAD

**Issue by willcollie1** [dickreuter/Poker#120]
I have run the script main.py as per the instructions laid out and upon hitting 'Start' the bot does not act.

Log reads as follows:

```
2021-01-07 21:25:10,403 - WARNING - table_scraper.py - get_my_cards2 - 62 - My cards not recognized
2021-01-07 21:25:10,404 - INFO - table_scraper.py - get_my_cards2 - 63 - My cards: []

```
Script being run from Windows 10 on my machine.
Poker Client running in VirtualBox (also running Windows 10)

VirtualBox screenshot looks like:
![screenshot_vbox](https://user-images.githubusercontent.com/29179974/103948580-e14b7c00-5131-11eb-8a86-43d458c3387a.png)

From FAQ section I cannot work out the issue. Do you have any suggestions I could try?

Happy to update FAQ if they work. Thanks

**Comment by dickreuter** [comment]
We have better table mappings available now that work well
