### ISSUE TITLE
Tesseract misreading dollar sign as 5 or 7

### ISSUE THREAD

**Issue by OJBru** [dickreuter/Poker#128]
Any tips on how to avoid tesseract misreading the dollar sign? I tried to reduce the coordinates to exclude it but this in turn causes in issue when the value exceeds single digit dollar values. Experiencing this on PokerStars client in default theme.

**Comment by dickreuter** [comment]
What configuration are you using? Which table scraper have you selected?

**Comment by OJBru** [comment]
Seems its only effecting pot values while using grey felt, working as intended on green felt so no action required. Thanks
