### ISSUE TITLE
Some cards in GG

### ISSUE THREAD

**Issue by canfron** [dickreuter/Poker#142]
**Describe the bug**
The system changes some cards. The 6H.png is a 4H really. I think I've seen any other like TD.png been a TD but I have no photo.

**Screenshot png file from the log\screenshots folder**
![6H](https://user-images.githubusercontent.com/11422868/126479569-8d9a6069-bed5-488d-82fa-0645fb5e8d93.png)

**Comment by dickreuter** [comment]
you need to retrain the table and put this card into the 4h folder
