### ISSUE TITLE
macOS app?

### ISSUE THREAD

**Issue by mabeljarsdel** [dickreuter/Poker#145]
Hi there,

Do you have an macOS app?

Regards

**Comment by dickreuter** [comment]
Not at the moment.

**Comment by mabeljarsdel** [comment]
@dickreuter, is it possible to run it on macOS?

**Comment by kirill-cy** [comment]
Bot is successfully running on Mac OS Catalina. It's not inside virtualbox, btw

![Screenshot 2021-11-28 at 5 00 29 PM](https://user-images.githubusercontent.com/34485568/143773922-01569820-a45f-488b-ad7e-9fcea5672760.png)

**Comment by logicappsource** [comment]
@kirill-cy  Did it work out successfully let me know :)? Did u try stars

**Comment by logicappsource** [comment]
`Traceback (most recent call last):
  File "/Users/aa/Desktop/Poker/Poker/poker/main.py", line 313, in <module>
    run_poker()
  File "/Users/a/Desktop/Poker/Poker/poker/main.py", line 300, in run_poker
    gui_signals = UIActionAndSignals(ui)
  File "/Users/aa/Desktop/Poker/Poker/poker/gui/action_and_signals.py", line 203, in __init__
    idx = available_tables.index(table_scraper_name)
AttributeError: 'dict' object has no attribute 'index'`

Please help on macos to run it

**Comment by dickreuter** [comment]
New version is now compatible with mac
