### ISSUE TITLE
Bot full

### ISSUE THREAD

**Issue by pedrofeliz90** [dickreuter/Poker#153]
Hello, I couldn't understand the advantage of subscribing to the full bot, and I saw in some comments that the source code is free, but the Data is paid, what would that Data be?  
I saw some threads, stating that the server was offline.  
This server is the Database that you sell?

**Comment by pedrofeliz90** [comment]
ok, for me to understand, an open source project here on GitHub, it's not the full version is it?

**Comment by pedrofeliz90** [comment]
File "C:\Users\Junior\Downloads\Poker-master(1)\Poker-master\poker\tools\screen_operations.py", line 12, in <module>
    from tesserocr import PyTessBaseAPI, PSM, OEM
ModuleNotFoundError: No module named 'tesserocr'

I installed the modules and it's still giving this error, what is the possible problem, I'm using pycham

**Comment by baal1986** [comment]
> File "C:\Users\Junior\Downloads\Poker-master(1)\Poker-master\poker\tools\screen_operations.py", line 12, in from tesserocr import PyTessBaseAPI, PSM, OEM ModuleNotFoundError: No module named 'tesserocr'
> 
> I installed the modules and it's still giving this error, what is the possible problem, I'm using pycham

Are you fix this problem? How?

**Comment by pedrofeliz90** [comment]
I don't remember, I don't think I managed to fix it. I used his program, and I rented his service for 1 month, he provides several strategies, which users register, but I couldn't find any profitable, I tested several times, but without success.
The program itself does its job, which is to move the mouse and click in the right place. The hard part is getting the strategies right.
