### ISSUE TITLE
Connection refused when running code on Mac

### ISSUE THREAD

**Issue by HUNTINGHOUND** [dickreuter/Poker#162]
**Describe the bug**
Hi I'm tring to run the python code on Mac by resolving all the dependencies and it's showing a connection error. 

**Screenshot png file from the log\screenshots folder**
<img width="1196" alt="Screen Shot 2022-11-02 at 4 27 50 PM" src="https://user-images.githubusercontent.com/75761291/199595896-d1b9e227-e75c-47d1-a6ed-b6e81201cf9f.png">

**Log information**
requests.exceptions.ConnectionError: HTTPConnectionPool(host='dickreuter.com', port=7777): Max retries exceeded with url: /get_internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1492d7bd0>: Failed to establish a new connection: [Errno 61] Connection refused')) can anyone help?

**Comment by dickreuter** [comment]
mac is now working
