### ISSUE TITLE
Bot only fast folds on PS.

### ISSUE THREAD

**Issue by agcampelo** [dickreuter/Poker#166]
I'm using a VNC connection to another computer and the bot works just fine until it's time to do anything other than fast fold or fold on a preflop with no action.

If it has to call/raise/fold to any action it just stops, I'm timed out and the bot proceeds to click on "I'm back".

Is this a known issue?

Thanks in advance.

**Comment by cdsimmons** [comment]
Just guessing, but could be an issue with VNC. Maybe try get it running with a VM instead to confirm.

**Comment by dickreuter** [comment]
use a different strategy
