### ISSUE TITLE
pokerbot_downloader.exe

### ISSUE THREAD

**Issue by jjunior89** [dickreuter/Poker#169]
I am not able to install the program

![image](https://user-images.githubusercontent.com/36820280/228050618-1e911243-eb52-4825-90fa-8c7a0490f885.png)

**Comment by dickreuter** [comment]
Please try again now

From: jjunior89 ***@***.***>
Date: Monday, 27 March 2023 at 20:49
To: dickreuter/Poker ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dickreuter/Poker] pokerbot_downloader.exe (Issue #169)

I am not able to install the program

[image]<https://user-images.githubusercontent.com/36820280/228050618-1e911243-eb52-4825-90fa-8c7a0490f885.png>

**Comment by jjunior89** [comment]
working, thx

**Comment by dickreuter** [comment]
delete and reinstall
