### ISSUE TITLE
Cant install packages locally

### ISSUE THREAD

**Issue by cdsimmons** [dickreuter/Poker#170]
**Describe the bug**
Followed steps to install Anaconda and PyCharm. Ran the command to install packages with conda, and received loads of errors with packages being incompatible with each other and the python version. 

Reduced python version to 3.10.9, and set all package versions to x.* to make them wildcard. Still getting weird package installation errors. Tried the same steps with Windows, Docker, and MacOSX, but still experiencing same issues with installing the packages required.

**Comment by dickreuter** [comment]
It works with python 3.11. Please send a specific error message and I can help.
