### ISSUE TITLE
Pin pyhon dependencies

### ISSUE THREAD

**Issue by nicolaslattuada** [dickreuter/Poker#173]
**Describe the bug**
Cannot do pip install -r requirements.txt

**Screenshot png file from the log\screenshots folder**
Fails because there are conflicting versions for numpy, pyqtwebengine and daal

**Log information**
Please can you do pip freeze > requirements.txt, so that your dependencies gets pinned, and its easier for new joiner to install the project

Thanks a lot !

**Comment by dickreuter** [comment]
added requirements_fixed.txt

**Comment by nicolaslattuada** [comment]
Thanks a lot !
