### ISSUE TITLE
PokerStars Broken! Needs Urgent Remapping

### ISSUE THREAD

**Issue by keithorange** [dickreuter/Poker#175]
**Describe the bug**
PokerStars updated their UI slightly. Their Call/Fold/Raise buttons are now Bright Red and so the maps no longer works.

**Screenshot png file**
![Screenshot 2023-05-04 at 4 38 01 PM](https://user-images.githubusercontent.com/130861337/236323679-ca0dc7f2-ec35-499b-87ee-dc1f1122b0cf.png)

**TODO**
Remap the official pokerstars ui map and quickly push the changes.

**Comment by keithorange** [comment]
INFO - Call button found: False
INFO - Raise button found: False
INFO - Bet button found: False
INFO - Check button found: False
INFO - Test finished.

**Comment by dickreuter** [comment]
you can remap it with the table mapper. In the documentation there is a video description how to do it. Happy to give free premium for anybody who manages to map it well.

**Comment by keithorange** [comment]
Can we add a feature to have quicker remmapping on ui updates? Why bother remapping the entire image when an update occurs when we can import the new image and remap only the changes? Can we add this feature?

**Comment by keithorange** [comment]
Also, there are other PokerStars mappings that are provided (5-10 different version). Do you have screenshots for what they are mapped too? It could be easier just to switch the default mapping

**Comment by dickreuter** [comment]
If only an image has changed, you can easily copy an old table and then just adjust the changes.

**Comment by keithorange** [comment]
Yes I managed to remap it. What file is it saved to? I can send you that file

**Comment by dickreuter** [comment]
Just tell me the table name you mapped it to and we can rename it to
official poker stars.

**Comment by keithorange** [comment]
(New) Official Poker Stars. Did it get uploaded to a centralized db? What else is uploaded?

**Comment by dickreuter** [comment]
The tables are all stored on a centralised database.
