### ISSUE TITLE
ModuleNotFoundError: No module named 'poker'

### ISSUE THREAD

**Issue by Lenny4** [dickreuter/Poker#180]
# 1 When I try to launch in command line

### Conda env
```
conda create --name Poker -c conda-forge python=3.11
```

### Dependecies have been installed successfully
```
(Poker) alexandre@alexandre:~/Documents/Project/Poker$ pip install -r requirements.txt // no error
```

### Error
```
(Poker) alexandre@alexandre:~/Documents/Project/Poker$ python --version
Python 3.11.3
(Poker) alexandre@alexandre:~/Documents/Project/Poker$ python poker/main.py
Traceback (most recent call last):
  File "/home/alexandre/Documents/Project/Poker/poker/main.py", line 18, in <module>
    from poker.decisionmaker.current_hand_memory import (CurrentHandPreflopState,
ModuleNotFoundError: No module named 'poker'
```
# 2 When I try to launch with my idea (PyCharm)

Got error:
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/alexandre/miniconda/envs/Poker/lib/python3.11/site-packages/cv2/qt/plugins" even though it was found.
```
![image](https://github.com/dickreuter/Poker/assets/25544892/001344c6-af89-46e5-a530-984a3a0bf557)

What am I missing here ?

**Comment by dickreuter** [comment]
1. I suspect you don't have the right working directory in pychrm. Make sure the project is opened in the top folder (Poker) and then launch main.py.
2. Make sure to install both pyqt5 and pyq6 with pip install

**Comment by Lenny4** [comment]
https://stackoverflow.com/a/68058308/9033534

> sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

**Comment by Lenny4** [comment]
It was the `PYTHONPATH` env var.

See: https://stackoverflow.com/a/23210066/6824121
