### ISSUE TITLE
Feature Suggestion - Turn of autoplay / analysis only mode

### ISSUE THREAD

**Issue by manilevian** [dickreuter/Poker#198]
**Describe the bug**
Well its not a bug and I am unsure if this is possible at the moment. I would like to use this as a RTA and not as a Bot, so it would be great if we could turn of the bot and only have a solver connected to it. This way we could see some help without the bot playing completely by its own. I would actually love to have something like that. Id even pay for this feature :D!
I would messaged you directly @dickreuter but i couldnt find any info on your website or anything. if your interessted you can simply write me a mail on marxmichnichtvoll@gmail.com 

**Screenshot png file from the log\screenshots folder**
None

**Log information**

**Comment by dickreuter** [comment]
This feature is already available. in the main GUI you should see a tickbox called autoplay that you can untick. Let me know if this works.

**Comment by dickreuter** [comment]
In fact, the tickbox is called 'act automatically'
