### ISSUE TITLE
"increased required equity" message generated preflop

### ISSUE THREAD

**Issue by timeyyy** [dickreuter/Poker#200]
**Describe the bug**

The following log message is generated preflop 
`INFO - Other player has no initiative and there is no check button. Activate increased required equity for betting`

**Log information**

INFO - +++========================== NEW HAND ==========================+++
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Screenshot taken
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
WARNING - No dealer found.
INFO - Bot position is UTG+3
INFO - Dealer position (0 is myself and 1 is next player): 0
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Total Strategy winnings: -1.4
INFO - Winnings in BB per 100 hands: -1400.0
INFO - Game #5 - Last 100: $-1.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? False
INFO - Screenshot taken
INFO - My cards: ['3H', 'AH']
INFO - Player funds: [76.4]
INFO - my_funds: 76.4
INFO - Table cards: []
INFO - ---
INFO - Gamestage: PreFlop
INFO - Cards on table: []
INFO - ---
INFO - Dealer found at position 4
INFO - Bot position is UTG+5
INFO - Dealer position (0 is myself and 1 is next player): 4
INFO - Is it my turn? True
INFO - Check button found: False
INFO - Check button NOT found
INFO - Players in game: [0, 1, 3, 4]
INFO - Current round pot -1 (before processing)
INFO - Total pot 11.0
INFO - Player pots: [0, 2.0, 0, 0, 2.0, 0]
INFO - First raiser utg+0
INFO - Highest raiser abs: 0.0
INFO - First caller utg+3
INFO - Other player has initiative: False
INFO - Final Total Pot Value: 11.0
INFO - Current round pot 11.0 (after processing)
INFO - Call button found: True
INFO - Raise button found: True
INFO - Call value: 1.0
INFO - Raise value: 3.0
INFO - Final call value: 1.0
INFO - Final bet value: 3.0
INFO - Preflop reverse tables for ranges for opponent: NO
INFO - Absolute equity (no ranges for bot) 0.6
INFO - Use absolute equity
INFO - Preflop adjustment from position UTG+5: -0.05
INFO - Preflop adjustment from position and raisers 0.0
INFO - Preflop adjustment from position, raisers and callers 0.02
INFO - Other player has no initiative and there is no check button. Activate increased required equity for betting
INFO - Make preflop decision based on equity, not using preflop table
INFO - Equity: 60.0% -> 2 (3-3+1) Plr
INFO - Final Call Limit: 0.11 --> 1.0
INFO - Final Bet Limit: 0.01 --> 3.0
INFO - Pot size: 11.0 -> Zero EV Call: 9.99
INFO - +++++++++++++++++++++++ Decision: Fold+++++++++++++++++++++++
=== Press Enter to continue ===

**Comment by dickreuter** [comment]
It appears that the log message is wrong. In fact, it only activates the increased equity if the strategy tickbox is checked and for preflop this isn't available. 

I'll make this more clear in the next version, but it will have no change on the playing, just the log message is wrong.
