### ISSUE TITLE
Bot confused by the 8D card and makes mistakes (GGPoker)

### ISSUE THREAD

**Issue by Slimbips** [dickreuter/Poker#201]
Hello,

I see the bot has issues with the 8d card, sometimes it sees the card while it isnt there and than sees 6 cards on the table wich is impossible (check screenshot

![diamonds](https://github.com/dickreuter/Poker/assets/141335990/6bee2c99-a3fb-4e87-b756-2451e839f1de)

Maybe the 6d and 8d are to much lookalike?

**Comment by dickreuter** [comment]
do you have a png file?

**Comment by Slimbips** [comment]
![8dfault](https://github.com/dickreuter/Poker/assets/141335990/5155bb23-d834-4ec6-9b70-1e68a6db5d7f)

**Comment by dickreuter** [comment]
It does seem that the tolerance needs to be slightly adjusted. I'll release a fix later today. Good catch!
