### ISSUE TITLE
Cant find top left corner on some tables

### ISSUE THREAD

**Issue by Slimbips** [dickreuter/Poker#202]
Hello,

The program has some issues of detecting the top left corner, 1 is for poker now wich is an browser pokergame,
the other one is using anydesk on a tablet.

check the ss
![Screenshot 2023-08-13 114629](https://github.com/dickreuter/Poker/assets/141335990/76520be3-52be-43d2-b550-a3625b7815fe)

![tablet](https://github.com/dickreuter/Poker/assets/141335990/2de10904-f526-4da0-a9f2-3d385ef32891)

**Comment by dickreuter** [comment]
what did you choose as top left corner? There is no reason why it should have problems, as long as the top left corner always looks exactly the same.

More details required

**Comment by Slimbips** [comment]
![topleft](https://github.com/dickreuter/Poker/assets/141335990/e04f9e11-9a1d-4bf1-80f2-bcd24e6664a0)

**Comment by dickreuter** [comment]
the topleft corner seems to be just a dot. It finds multiple topleft corners.

**Comment by dickreuter** [comment]
it created a copy of the table and saved a new top left corner, it works fine
