### ISSUE TITLE
Table setup for tablet (GGPOKER) (so u can use anydesk or teamviewer) "undetectable"

### ISSUE THREAD

**Issue by Slimbips** [dickreuter/Poker#203]
Table setup for tablet doesnt work, this is the png

![tablet](https://github.com/dickreuter/Poker/assets/141335990/4c7db4b5-846f-4af6-b26c-3e6fd4954610)

cant find the left top corner and when u crop it it crops a complete different part of the table

**Comment by dickreuter** [comment]
what table template are you using and what did you mark as top left corner?

**Comment by Slimbips** [comment]
i created a new template, at least i wanted to but it wont let me get the top left corner,

tried multiple things, save the image to your desktop and try it yourself, i cant manage it

**Comment by dickreuter** [comment]
I just tried it and it works fine. I create a new table. Then I marked the top left corner as in the screenshot below, saved the new top left corner, then cropped. All worked fine.


![image](https://github.com/dickreuter/Poker/assets/1256318/6eaf7fc5-ef79-4ddf-b0c9-b768d45c54a9)
