### ISSUE TITLE
Partypoker funds

### ISSUE THREAD

**Issue by swizes** [dickreuter/Poker#21]
While playing at partypoker with real money if the amount is $4,52, the bot recognizes only "52" part. Which may cause strategy conflicts.

**Comment by swizes** [comment]
Issue solved, the format in windows must be changed

**Comment by dickreuter** [comment]
So the issue is resolved?

**Comment by swizes** [comment]
Hi,

I realized that the problem is that the cropped images for

get_other_player_pots
get_bot_pot
get_other_player_funds
get_total_pot_value
get_my_funds
get_current_call_value
get_current_bet_value

those methods are not correct for play money and sng tournaments (eg: 3,000 a.k.a chip amount instead of real money amount)

The coordinates for those functions must be changed. I am changing them right now and testing them on play money tables.

If you could give me recommendation about a software, where i can check the x1,x2,y1,y2 coordinates of selected rectangle of an screenshot would make my job more easy.

Cheers!

**Comment by dickreuter** [comment]
Sure, if you change them make sure to rebase your fork to get the latest
version.

Then create a new table version (don't overwrite the old ones). Best
connect with me on google hangouts on dickreuter@gmail.com so I can show
you how to do it.

**Comment by dickreuter** [comment]
Yes it needs to be uk format. Ok I need to add this to the description.
Thanks

**Comment by swizes** [comment]
can you post a screenshot of your region settings for currency and numbers? I have tried several times to make it work, but it didn't work, may be i am missing something. I will contact with you on google hangouts

**Comment by dickreuter** [comment]
let's talk about this on google hangout
