### ISSUE TITLE
Equity percentage is not calculated - no call bets are made because of this

### ISSUE THREAD

**Issue by ShestakovPD** [dickreuter/Poker#211]
![607738471_Flop_1](https://github.com/dickreuter/Poker/assets/46515809/e0cfcb46-9f4b-428d-a688-31d8747bf73f)
[log no calc equty.txt](https://github.com/dickreuter/Poker/files/13446039/log.no.calc.equty.txt)
people give your analysis in the comments, is there a call on the flop here? and should equity be calculated as a percentage and influence the decision made by the bot?

**Comment by aimeeaidanu** [comment]
I think you need to shut up
