### ISSUE TITLE
OCR incorrect MyFunds

### ISSUE THREAD

**Issue by aldaff89** [dickreuter/Poker#22]
OCR of MyFunds is detecting 8 as B. I had 867 but it detected as B67, then MyFunds final value was 67.  It also detected 489.25 as 39.25 and 1,003 as .003.

**Comment by swizes** [comment]
the screenshot for funds are small thats why it doesnt see before comma and the ocr does not replace comma. The coordinates must be changed

**Comment by dickreuter** [comment]
Make sure to switch to UK as country in your windows geography settings so that it doesn't use a comma but a dot instead. Also the $ needs to be before and not after the value. I'll see how I can improve the OCR so that B is replaced with an 8.

**Comment by dickreuter** [comment]
The problem is that the system is set up for U.K. Number convention where
the $ is before the number and instead of a , there is. .  You need to
change your country settings in windows.
