### ISSUE TITLE
Exception  caused by gui_signals.signal_lcd_number_update

### ISSUE THREAD

**Issue by swizes** [dickreuter/Poker#24]
Hi, 

i am facing with the exception (see screenshot) I have no idea, what my cause this. It does not happen everytime...

![exception](https://cloud.githubusercontent.com/assets/8876645/19777510/2e6feb98-9c81-11e6-9585-54594bd6da1e.PNG)

**Comment by swizes** [comment]
Can it be the reason that the ocr cant convert the str to float thats why the second argument is passed as string?

**Comment by dickreuter** [comment]
Sent you a chat

**Comment by dickreuter** [comment]
If you search for if 
`self.currentCallValue == '':` in get_current_bet_value function
you find the code that will catch the case where the number cannot be converted into a float (it will end up as an empty string) and the value is replaced by 99999. So not sure why this can happen.
