### ISSUE TITLE
Exception with PS

### ISSUE THREAD

**Issue by farina99** [dickreuter/Poker#25]
Get temporarily rip off #20 issue with fake one .png but get immediatly after this error:
![error](https://cloud.githubusercontent.com/assets/22627741/19787807/ffd994b8-9ca4-11e6-8d3e-4589259ddf71.jpg)

Any suggestion?

**Comment by dickreuter** [comment]
Talbe PS is currently not in use. For pokerstar choose PS2 (in strategy
editor on the table setup tab), which is the 5 table version for zoom
games. All in button is still missing for that one though. Otherwise choose
PP for Partypoker where it works all fine.
