### ISSUE TITLE
Screen resolution and OS in VM

### ISSUE THREAD

**Issue by delijati** [dickreuter/Poker#3]
I got the system up and running under ubuntu but unfortunately ``matchTemplate`` can't get a match. Could you please explain witch font, screen resolution and OS you are using in the vm.

**Comment by dickreuter** [comment]
I have tested it on windows only. Are you using partypoker?

**Comment by delijati** [comment]
Yes i use partypoker

**Comment by delijati** [comment]
The problem seems to be the templates, they are not matching with my screenshots. I think the images have to be nearly "pixel perfect".

**Comment by dickreuter** [comment]
yes they have to be perfect matches at the moment. If you find a better way
you're welcome to improve that, but they are all very similar so I found
this to be the only working solution.
