### ISSUE TITLE
How do poker clients detect that a bot is running ? Can they do so across Wine ?

### ISSUE THREAD

**Issue by Mouradif** [dickreuter/Poker#42]
Hello,

This is not an issue, just a question.

The fact that Poker clients are able to detect that the bot is running made me question myself a lot about how they could do this. Do they simply look for a suspicious process name in the list of currently running processes ? Are they able to determine that the cursor moved but the mouse didn't ? Can they still detect if a bot is running if the poker client is launched via Wine (on Mac) or do we require a full OS installation on a virtual machine ?

I have thought of running this script via a USB device that reads the screen video stream and simulates physical mouse and keyboard. Would that be stealthy enough ?

**Comment by dickreuter** [comment]
I don't know. Best ask in a forum but I'm not familiar with wine. Pokerstars takes screenshots so they would see whatever is going in the environment the client is running. But they would be be able to see outside.
