### ISSUE TITLE
Possibility to change player position for Pokerstars

### ISSUE THREAD

**Issue by mareurs** [dickreuter/Poker#48]
Hi, I am testing on PS and it seems to be running well. I want though to be possible to start the bot with a parameter like player index position. Based on that, a new coordinates file to be generated. This will give us the possibility to choose more tables and fly better under the radar :). I will try to do that and let you know.

**Comment by dickreuter** [comment]
Sure but that will involve a bit of work and I don't think you should
dynamically create the coordinates file, but rather when loading it turn
the players around.

Did you make any enhancements for ps and the image files? To make it run
this would have been necessary.

**Comment by mareurs** [comment]
Yes, I made minor changes to pot places and pot bet I think. I tested it on the "Play money" not "Real money" and I have some errors with the pots being read as "\d{1,2}.\d{1.2}", so basically floats which is not the case for "Play money". I will test it on real money and if everything works I can make a commit. If there is anything that you need please let me know.

**Comment by dickreuter** [comment]
Ok that's great. You will also need to update the screenshots in pics/ps
for imback and allincall.

Regards
