### ISSUE TITLE
Debug: Top left corner NOT found

### ISSUE THREAD

**Issue by mrjindal** [dickreuter/Poker#5]
Hi, I am following the setup as per the instructions but I am getting the following debug once I start the bot:

Top left corner NOT found. 

I am getting the same message with both Win10 and Direct Mouse Control. Could you please advise? 

P.S. I am new here

**Comment by mrjindal** [comment]
I am running pokerstars btw, thanks in advance :)

**Comment by dickreuter** [comment]
Make sure not to scale the windows and the full window of the table needs to be visible as in the screenshot examples. Make sure to choose a strategy that is for Pokerstars. For now we are still testing with partypokers but pokerstars should work as well.

**Comment by dickreuter** [comment]
New version now available.
