### ISSUE TITLE
site interface 

### ISSUE THREAD

**Issue by brw31415** [dickreuter/Poker#50]
i'd like to try this on play money site like https://www.replaypoker.com .

where do i find the way the interface code? thanks

**Comment by dickreuter** [comment]
Never heard of this site. Does it offer to play with real money? If so we can add it in the coordinates file.

**Comment by brw31415** [comment]
no, its strictly play money, but it is very active with good players honing
their chops, so i thought it would be a good test site

**Comment by keterslayter** [comment]
Can you please help me too? I would like to play with the bot on this site :
www.7XL.com
(For playing you need to download the software from the site) 
and another question , is it able to play tournaments too? Or only cash games

Thank you for your support

**Comment by dickreuter** [comment]
send me some screenshots and I'll see if it makes sense to add it. Is it
only play money as well?

**Comment by brw31415** [comment]
![image](https://user-images.githubusercontent.com/11561427/31587074-eced622a-b1a8-11e7-963f-81be69f54420.png)

**Comment by dickreuter** [comment]
At this time I prefer to focus on tables with real money only as the behaviour with play money is very different.
