### ISSUE TITLE
vm_control - ERROR

### ISSUE THREAD

**Issue by mda6** [dickreuter/Poker#51]
I get the error:

vm_control - ERROR - (-2147221005, 'Invalid class string', None, None)

I installed windows xp with VMware 

I tried starting the bot on McNaught table on Pokerstars and the bot couldn't find the client ... 'PP not found yet'

Thanks

**Comment by dickreuter** [comment]
Did you check the FAQ? Did you switch to direct mouse control?

**Comment by mda6** [comment]
I did, however what i did not do is change to ps from pt in the strategy dropdown menu (that recognized the client) and it worked... for a moment, i kept getting 2 messages after that, that the position couldn't be recognized and that it assumed it's UTG, the other message i kept getting is that it couldn't get the price correctly (something like that)..

I also wanted to ask you were they reported bans for using your bot on pokerstars - with the use of virtual machine of course. 

Thank you!

**Comment by dickreuter** [comment]
No, it’s not possible to see outside the vm. So no bans.
