### ISSUE TITLE
ServerSelectionTimeoutError: dickreuter.com:27017: timed out

### ISSUE THREAD

**Issue by Rotaka92** [dickreuter/Poker#53]
Hey, 

the threadname is the error i get when i want to check_update(version) in the main.py.
Whats the problem here? I am not that skilled in mongodb and i am using spyder.

Thanks

**Comment by Rotaka92** [comment]
Ok, think i have to run a MongoDB instance first before i can go further, right?

**Comment by dickreuter** [comment]
No, you just need to update the code. When did you clone it?

**Comment by Rotaka92** [comment]
Cloned it two days ago

**Comment by dickreuter** [comment]
Rebase it to the lates version

**Comment by Rotaka92** [comment]
it works, thanks! =)
