### ISSUE TITLE
Bot uses wrong coordinates for call button since change to coordinates.json

### ISSUE THREAD

**Issue by haxnpeter** [dickreuter/Poker#57]
hi, after some debbuging and wondering why the bot always raises instead to call (when it shows call in the bot window) i found out, that it uses the wrong coordinates for pokerstars.

all other buttons are working right and the coordinates from the ps2 section are getting used, but the call button uses the coordinates from the ps section. (and that coordinates point to the raise button) 

a temp fix is, to change the ps call button coordinations, but i guess it is not intended that all other buttons use the PS2 section and only for the call button the PS section is used.

**Comment by groZeuros** [comment]
Ok, will have a look.

**Comment by dickreuter** [comment]
@groZeuros can you have a look please, so we can avoid a revert? thanks

**Comment by dickreuter** [comment]
New contribution is merged. Does this fix the problem?
