### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by dickreuter** [dickreuter/Poker#59]
@groZeuros
groZeuros, it seems that the tests in tests/test_tableScreenBased are now failing. Could you have a look if this is cause of concern? thanks

**Comment by groZeuros** [comment]
Hello, I'll try to have a look, but I have very few time these days

greetings

2018-02-21 0:25 GMT+01:00 Nicolas Dickreuter <notifications@github.com>:

**Comment by dickreuter** [comment]
reverted
