### ISSUE TITLE
partypoker wont work after update

### ISSUE THREAD

**Issue by JumpiJumpi** [dickreuter/Poker#64]
hi there,

always have this message:
2018-03-15 20:59:09,115 - table - DEBUG - Top left corner found
2018-03-15 20:59:09,158 - table - DEBUG - Did not find two player cards: []

after update the default window change a bit look here

![table](https://user-images.githubusercontent.com/37420280/37489257-4f429c1e-2897-11e8-9e2d-1a1d882415e1.png)

the bottom of the window is different. Anyone the same fault? or my fault? Lower Frame has gone.

**Comment by dkendrick** [comment]
I am experiencing the same problem - I was really looking forward trying it out!

**Comment by andersbreivik** [comment]
same problem. Any solution?
