### ISSUE TITLE
Not doing anything besides clicking "I'm back"

### ISSUE THREAD

**Issue by Footurist** [dickreuter/Poker#65]
I've tested with both PartyPoker and Pokerstars and on both clients the only thing it does it recognizing the "I'm back" button and clicking it. After that nothing happens. What could that be?

**Comment by mutonby** [comment]
U need to change the pics, with new screenshots because It changes

**Comment by dickreuter** [comment]
Which one? Pokerstars or partypoker?

**Comment by mutonby** [comment]
I am speaking of partypoker, I needed to change some pics for run the program

**Comment by mutonby** [comment]
I can do a pull request If u want

**Comment by dickreuter** [comment]
Ok, please create a pull request of your changes

**Comment by mutonby** [comment]
Okk, I only changed the pics, no the code, because I can't run the main.py, I setup anaconda environment but I Can't run de python, some tips?  

thanks.

**Comment by dickreuter** [comment]
Did you follow the instructions on the wiki how to build the virtual environment?

**Comment by mutonby** [comment]
Yes I builded the environment with conda, and later? I tryed to follow the compile.sh un Windows sintaxis

**Comment by dickreuter** [comment]
No you don’t need complie.sh. You need to run main.py from pycharm with the new virtual environment.

**Comment by mutonby** [comment]
always get this error:

line 17, in <module>
    from poker.gui.gui_qt_ui import Ui_Pokerbot
ImportError: No module named 'poker'

**Comment by mutonby** [comment]
Ok I take it, need to import the poker folder to project ^^ Tomorrow I will pull request the changes.

thank u so much.

**Comment by Footurist** [comment]
Since I know some python, here's a solution for the module error : you can just insert the parent directory into the path via 
`sys.path.insert(0, "..")`
This way, python knows the right path.

**Comment by mutonby** [comment]
Thank u but I fixed this problem, included the folder poker in the pycharm project. 

My problem now is with pytesseract, I installed with conda dependencies but when I run de main.py always get the message: "tesseract not installed...."

**Comment by Footurist** [comment]
try installing it with pip in the python console : 
`python -m pip install pytest`
if you don' have pip installed, you need to install that first.

**Comment by SebastianBO** [comment]
Same for Pokerstars, anyone got it fixed or should I?

**Comment by Footurist** [comment]
anything new?

**Comment by andersbreivik** [comment]
still not working with current pics

**Comment by dickreuter** [comment]
New version now available
