### ISSUE TITLE
Install WIN10: Details error install tesseract

### ISSUE THREAD

**Issue by h4wk3r** [dickreuter/Poker#69]
Hello everyone.

Has anyone managed to install the repository on Widows 10?

I have a problem with the installation of tesseract-ocr.

ERROR:
  tesseract_ocr.cpp (463): fatal error C1083: Can not open include file: 'leptonica / allheaders.h': No such file or directory
  error: command 'c: \\ Program Files (x86) \ Microsoft Visual Studio 14.0 \\ VC \\ Bin \\ x86_amd64 \\ cl.exe' failed with exit status 2

Can someone help me?
Thank's

h4wk3r

**Comment by dickreuter** [comment]
I've added a link to tesseract in the setup wiki
