### ISSUE TITLE
MongoDB is down ?

### ISSUE THREAD

**Issue by aneopsy** [dickreuter/Poker#7]
Hi,
I am a Python dev and I like your project.
I would like contribute, but i can't access to mongodb://guest:donald@52.201.173.151:27017/POKER
Stdout: 'pymongo.errors.ServerSelectionTimeoutError: 52.201.173.151:27017: timed out'

thx, and good luck.

**Comment by dickreuter** [comment]
The mongodb works fine. Please try again or maybe you have firewall problems? Otherwise contact me on google hangouts dickreuter@gmail.com
