### ISSUE TITLE
somebody has a PP new pics

### ISSUE THREAD

**Issue by mattiaa95** [dickreuter/Poker#72]
somebody has the last photos necessary spara that the bot fucnione correctly in partypoker or poker star, it does not work in any of the two with this version :(

**Comment by dickreuter** [comment]
You need to screenshot them

**Comment by Kelturon** [comment]
how do i add the photos into the bot so it can recognise the table correctly? @dickreuter your project seems awesome, i want to start it and contribute. How is it possible to contact you?

**Comment by dickreuter** [comment]
new binaries are now available with a user interface to learn new tables.
