### ISSUE TITLE
Howto add further poker platforms? 

### ISSUE THREAD

**Issue by thiko** [dickreuter/Poker#74]
Hi,

I'm thinking about adding a further platform / diff. poker software.
Can you pls give me a short sum up, what I have to do?
In my imagine, I just have to make screenshots to find the top left corner, train the NN to recognize the cards and of course expand the coordinates.txt according your description in the wiki.

Would it be possible to use a different corner? I'm not sure about the usage. First I was thining, that you use that corner as a fix point to find all other card/buttons/... relative to that point. But the coordinates files looks like fix points at all.

Thanks in advance!

**Comment by thiko** [comment]
of course that would be very nice but sounds like a lot of work. pls trigger me, if you can delegate smth.

**Comment by sebastiaoRealino** [comment]
I was thinking about to add a new platform too. It's really too much complicated?

**Comment by dickreuter** [comment]
Do you have a screenshot of how it looks like?

As a start you would need to create templates of all the cards so it can recognise them correctly 100%.

**Comment by clappis** [comment]
@sebastiaoRealino send me a message on hangouts.

**Comment by sebastiaoRealino** [comment]
@dickreuter soon as possible, I will edit this post with screenshots. Ok?
@clappis I sent you an invite on hangouts.

**Comment by carlosfusion** [comment]
Hello did any one add the pppoker layout so can share?

@dickreuter how can i contact you?

**Comment by dickreuter** [comment]
new binaries are now available with a user interface to learn new tables.
