### ISSUE TITLE
i want to pay bot

### ISSUE THREAD

**Issue by yudiaswar** [dickreuter/Poker#75]
i want to pay bot casino game from www.nagapoker.com
can anyone make me a casino bot at www.nagapoker.com? I will pay. thanks

**Comment by tiounaev** [comment]
easy

**Comment by dickreuter** [comment]
Best go to Upwork.com. Plenty of people for hire there.

**Comment by tiounaev** [comment]
I completely agree

**Comment by tiounaev** [comment]
> Лучший перейти к Upwork.com. Там много людей для найма.
> […](#)
> 2 февраля 2019, в 03: 04, yudiaswar ***@***.***> писанное: я хочу платить бот казино игры от [www.nagapoker.com](http://www.nagapoker.com) может ли кто-нибудь сделать меня ботом казино [www.nagapoker.com ](http://www.nagapoker.com)? Я заплачу. Спасибо — Вы получаете это, потому что вы подписаны на этот поток. Ответьте на это письмо напрямую, просмотрите его на GitHub или отключите поток.

I completely agree

**Comment by tiounaev** [comment]
> Best go to Upwork.com. Plenty of people for hire there.
> […](#)
> On 2 Feb 2019, at 03:04, yudiaswar ***@***.***> wrote: i want to pay bot casino game from [www.nagapoker.com](http://www.nagapoker.com) can anyone make me a casino bot at [www.nagapoker.com](http://www.nagapoker.com)? I will pay. thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I completely agree

**Comment by tenisakb** [comment]
Hi,
If you are still interested, let me know, I can do it for you.
ladislav.balon@viptrust.com
https://en.viptrust.com
