### ISSUE TITLE
background wallpaper file link is broken on the WIKI

### ISSUE THREAD

**Issue by suctionseat** [dickreuter/Poker#77]
Looking at the setup instructions on the wiki, the background image link seems to be broken:

Wiki link: https://github.com/dickreuter/Poker/wiki/Setup-instructions

Pic link: https://github.com/dickreuter/Poker/raw/master/wiki/VM_background_1280_720.png?raw=True

**Comment by dickreuter** [comment]
Please fix and create PR

**Comment by chordgitarmudah** [comment]
`
<a href="http://www.18dewapoker.asia/">poker online</a><br />
<a href="http://www.18dewapoker.asia/">18dewa</a><br />
<a href="http://www.18dewapoker.asia/">18dewapoker</a><br />
<a href="http://www.18dewapoker.asia/">judi online</a><br />
<a href="http://www.18dewapoker.asia/">situs judi online</a><br />
<a href="http://www.18dewapoker.asia/">ceme online</a><br />
<a href="http://bandar389.blogspot.com/">judi slot online</a><br />
<a href="http://bandar389.blogspot.com/">bandar 389</a><br />
<a href="http://bandar389.blogspot.com/">slot online</a><br />
<a href="http://bandar389.blogspot.com/">judi slot</a><br />
<a href="http://www.18dewapoker.asia/">idn poker&nbsp;</a><br />
<a href="http://www.18dewapoker.asia/">18 dewa</a><br />
<a href="http://www.18dewapoker.asia/">18 dewapoker</a><br />
<a href="http://www.18dewapoker.asia/">dewapoker</a><br />
<a href="http://www.18dewapoker.asia/">link alternatif 18dewa</a>

<a href="http://www.18dewapoker.store/">poker online</a><br />
<a href="http://www.18dewapoker.store/">18dewa</a><br />
<a href="http://www.18dewapoker.store/">18dewapoker</a><br />
<a href="http://www.18dewapoker.store/">judi online</a><br />
<a href="http://www.18dewapoker.store/">situs judi online</a><br />
<a href="http://www.18dewapoker.store/">ceme online</a><br />
<a href="http://bandar389.blogspot.com/">judi slot online</a><br />
<a href="http://bandar389.blogspot.com/">bandar 389</a><br />
<a href="http://bandar389.blogspot.com/">slot online</a><br />
<a href="http://bandar389.blogspot.com/">judi slot</a><br />
<a href="http://www.18dewapoker.store/">idn poker&nbsp;</a><br />
<a href="http://www.18dewapoker.store/">18 dewa</a><br />
<a href="http://www.18dewapoker.store/">18 dewapoker</a><br />
<a href="http://www.18dewapoker.store/">dewapoker</a><br />
<a href="http://www.18dewapoker.store/">link alternatif 18dewa</a>

<a href="http://18-dewa.blogspot.com/">poker online</a><br />
<a href="http://18-dewa.blogspot.com/">18dewa</a><br />
<a href="http://18-dewa.blogspot.com/">18dewapoker</a><br />
<a href="http://18-dewa.blogspot.com/">judi online</a><br />
<a href="http://18-dewa.blogspot.com/">situs judi online</a><br />
<a href="http://18-dewa.blogspot.com/">ceme online</a><br />
<a href="http://bandar389.blogspot.com/">judi slot online</a><br />
<a href="http://bandar389.blogspot.com/">bandar 389</a><br />
<a href="http://bandar389.blogspot.com/">slot online</a><br />
<a href="http://bandar389.blogspot.com/">judi slot</a><br />
<a href="http://18-dewa.blogspot.com/">idn poker&nbsp;</a><br />
<a href="http://18-dewa.blogspot.com/">18 dewa</a><br />
<a href="http://18-dewa.blogspot.com/">18 dewapoker</a><br />
<a href="http://18-dewa.blogspot.com/">dewapoker</a><br />
<a href="http://18-dewa.blogspot.com/">link alternatif 18dewa</a>

`

**Comment by dickreuter** [comment]
new binaries are now available with a user interface to learn new tables.
