### ISSUE TITLE
Update gui_qt_logic.py 

### ISSUE THREAD

**Issue by Jamaiaanaxxx** [dickreuter/Poker#82]
Traceback (most recent call last):
File "poker\gui\gui_qt_logic.py", line 326, in 
TypeError: init() takes 3 positional arguments but 4 were given

while using the Patrick Edward PS Zoom II strategy and pressing Genetic Algorithm.
Strategy Analyser also doesnt work for me, but dont now if that is related to this.

For the rest, really nice work!

**Comment by dickreuter** [comment]
did you manage to update the table coordinates? If so, please share them.
