### ISSUE TITLE
Unnecessary automation.

### ISSUE THREAD

**Issue by oakniiv** [dickreuter/Poker#83]
In my opinion automation on this is completely unnecessary, you should put your focus on making a terminal version that simply gives you advice on what to play next. Also I think that automation would be much more easily achieved through selenium and playing in browser. 
However, the project should really focus on decision making and printing the next best decision.
Two ways to do this, the bot looks at the game and collects data about what other players did and gives you advice, or we re-play other players actions and bot tells us what to do. 

Could you please make a version without automating the clicks with the decision making only? Thank you very much, great project btw and effort so far!

**Comment by holysheepcoder** [comment]
@oakniiv hi. did you use bot now? I have some troubles with this installation.

**Comment by oakniiv** [comment]
@holysheepcoder I did not test it yet I just factory re seted my windows, downloaded virtual machine and will try it out tomorrow on pokerstars. But this whole thing with the screen size and auto clicks is so unnecesarry I'd like to try the project to be a pure terminal and decision making.
I'd like to input what other players did and the terminal tells me what's the best decision to make. Or atleast have the program not control the gui this much, it is just slowing down the development and causing unnecessary issues like you see on the project. You resize the pokerstars screen and can throw the whole thing away...

**Comment by juanibal** [comment]
I also think this should be a decision support system. If someone creates something like this without all the automation let me know, i would be insterested.

**Comment by dickreuter** [comment]
I'm not aware of any poker client over the browser in partypoker or pokerstars.

**Comment by dirichletzz** [comment]
You can use hand2note or smth as a decision advisor. I think the automation based on screenshot and auto clicks is a general solution, comparing to a web-based way. And the automation, can be used to test the strategies, which are not able to be strictly executed by a human.
It's a very nice project.

**Comment by dickreuter** [comment]
new binaries are now available with a user interface to learn new tables.

**Comment by deadmouse** [comment]
> 
> 
> @holysheepcoder I did not test it yet I just factory re seted my windows, downloaded virtual machine and will try it out tomorrow on pokerstars. But this whole thing with the screen size and auto clicks is so unnecesarry I'd like to try the project to be a pure terminal and decision making.
> I'd like to input what other players did and the terminal tells me what's the best decision to make. Or atleast have the program not control the gui this much, it is just slowing down the development and causing unnecessary issues like you see on the project. You resize the pokerstars screen and can throw the whole thing away...

@oakniiv Did you find something like a terminal? Thank you
