### ISSUE TITLE
trouble to set VM and BOT  to the right size.

### ISSUE THREAD

**Issue by Scum1254** [dickreuter/Poker#87]
the link is not working anymore like mentioned in another post. the available screenshots are confusing me. which layout is needed, so that the bot finds top-left? 
can someone help me out? 

Wiki link: https://github.com/dickreuter/Poker/wiki/Setup-instructions

Pic link: https://github.com/dickreuter/Poker/raw/master/wiki/VM_background_1280_720.png?raw=True
> tip : If the software cannot read the virtual machine because you unluckily resized your PokerStars table window, Here is a beautiful background you can set as your virtual machine background, all you have to do then is to resize the VM screen to [1280,720], move the poker table window over the footprint, start the poker bot

>

**Comment by dropcunt** [comment]
I have to same problem. Did you find a solution?

**Comment by Scum1254** [comment]
check „table“   folders. there are two of them. check the py.files. there is one file that creates output pictures. Thise pictures shows you what or which area of the screen „he(the bot) receives. So just pass some test pics from an VM with the poker software in it. and check the out put file. 

The you can compare your test pic with the output pic. You need to make sure that the „top-left“ is in the out put file. 
also you need the new cordinate and new template pictures. hard to explain.  i am no a native english speaker. hope i could help or at least point you in the right direction.

**Comment by Scum1254** [comment]
the bot needs no specially Layout. It just needs to find top left  corner. and then it knows how wide or high the ROI needs to be.

**Comment by dropcunt** [comment]
thanks that helped me. So the table setup works now and it finds the table based on the top left corner. I updated some of the coordinates so the rectangles are in the right place.
Can you help me with the next steps? What did you do afterwards?

**Comment by dickreuter** [comment]
Can you create a pull request?

**Comment by dropcunt** [comment]
yes I will. I still have to clean up though

**Comment by seppemarotta** [comment]
@dropcunt I can clean it if you have the branch. I am trying to update those files aswell

**Comment by feniks30** [comment]
> проверьте «столовые» папки. Есть два из них. проверьте py.files. есть один файл, который создает выходные изображения. На этих рисунках показано, какую или какую область экрана он (бот) получает. Так что просто передайте несколько тестовых картинок с виртуальной машины с покерным программным обеспечением. и проверить выходной файл.
> 
> Вы можете сравнить свою тестовую картинку с выходной картинкой. Вы должны убедиться, что «верхний левый» (из ПО для покера внутри ВМ) находится в выходном файле.
> Также вам понадобится новый кординат и новые шаблоны картинок. сложно объяснить. Я не носитель английского языка. надеюсь, что смогу помочь или, по крайней мере, указать вам правильное направление.

Hi, I do not know. How to start and work with a bot, write me for later vladislavbarnes@gmail.com thanks in advance

**Comment by feniks30** [comment]
> check „table“ folders. there are two of them. check the py.files. there is one file that creates output pictures. Thise pictures shows you what or which area of the screen „he(the bot) receives. So just pass some test pics from an VM with the poker software in it. and check the out put file.
> 
> The you can compare your test pic with the output pic. You need to make sure that the „top-left“ (from the poker software inside the VM) is in the out put file.
> also you need the new cordinate and new template pictures. hard to explain. i am no a native english speaker. hope i could help or at least point you in the right direction.

Hi, I do not know. How to start and work with a bot, write me for later vladislavbarnes@gmail.com thanks in advance

**Comment by dickreuter** [comment]
new binaries are now available with a user interface to learn new tables.
