### ISSUE TITLE
Coordinates files

### ISSUE THREAD

**Issue by tommevans** [dickreuter/Poker#89]
Hello,

What are you using to transform the coordinates to an svg? I see you mention a few python scripts in the coordinates file wiki page but do not see the scripts. 

I've managed to get most of the tests working with the old images used in the library, I just don't see any easy / nice way of updating the coordinates.

Thanks

**Comment by dropcunt** [comment]
Hello tommevans

I'm running into the same problem.

Did you find out anything?

Thanks

**Comment by Arunavameister** [comment]
Have you guys figured out the solution yet?
I cant seem to be able to update the coordinates either

**Comment by higoramp** [comment]
Hi guys!
Just check the zeuros-table_scraper branch, there is a folder called tables inside poker with the files described on wiki

**Comment by dickreuter** [comment]
New version of the bot will be available shortly with a graphical tool to
learn new tables.

**Comment by higoramp** [comment]
Nice to hear about that!
Just discovered the project last week and I'm doing some tweaks to work on Linux.
Nice job!

**Comment by dickreuter** [comment]
new binaries are now available with a user interface to learn new tables.
