### ISSUE TITLE
Issues with MongoDB

### ISSUE THREAD

**Issue by Lemmie88** [dickreuter/Poker#92]
I am having connection issues with Mongo Client. I am getting a timeout error. Can you please advice?

**Comment by dirichletzz** [comment]
I think you can just comment the checkUpdate lines and run it again, if you build the app from source code.

**Comment by Elisson-damasio** [comment]
Same problem here. Did you solve it?

**Comment by dickreuter** [comment]
new binaries are now available with user interface to learn new tables
