### ISSUE TITLE
is functional today

### ISSUE THREAD

**Issue by ortiga88** [dickreuter/Poker#94]
is the bot currently working ?? or get banned

**Comment by dickreuter** [comment]
new version coming very soon with table setup gui

**Comment by ortiga88** [comment]
> nueva versión que viene muy pronto con la configuración de la mesa gui

when ???

**Comment by seppemarotta** [comment]
Hey, @dickreuter are you forking it somewhere? I want to help with it now that I have some time. Please let me know if I can help with some modules

**Comment by dickreuter** [comment]
Yes you’ll be able to help I’m around 2-3 weeks with mapping tables. Will
keep you posted.

**Comment by seppemarotta** [comment]
Great @dickreuter, just ping me!

**Comment by dickreuter** [comment]
new binaries are now available
