### ISSUE TITLE
it is valid for pokerstart ? 

### ISSUE THREAD

**Issue by ortiga88** [dickreuter/Poker#97]
at which pokerstars tables is it valid or has it been tested ???

**Comment by dickreuter** [comment]
Pokerstars has not yet been added. You are welcome to do it!

**Comment by ortiga88** [comment]
the link is down I can't download it

**Comment by dickreuter** [comment]
Which link? Have you tried this?

https://sourceforge.net/projects/partypoker-pokerstars-pokerbot/

**Comment by ortiga88** [comment]
yes

**Comment by ortiga88** [comment]
ok I have already been able to, what should be done to make it work in pokerstars?

**Comment by dickreuter** [comment]
added some initial description, hope this helps a bit: https://github.com/dickreuter/Poker/wiki/Adding-new-tables

**Comment by dickreuter** [comment]
added a short video to the wiki section on github that should help explain
it.
