### ISSUE TITLE
New instructions

### ISSUE THREAD

**Issue by SebastianBO** [dickreuter/Poker#98]
Running everything to executing main.py file, do I do this with conda run "main.py" or python3 main.py because both gives the error "ModuleNotFoundError: No module named 'matplotlib'" even tho Requirement already satisfied / requirement txt installed with pip install. The instructions are not 100 % clear meanwhile you've made a superb program

**Comment by dickreuter** [comment]
best use pycharm to run it and make sure to set the corresponding the virtual environment. Best check youtube how to handle pycharm.
