### ISSUE TITLE
Take Screenshot bug

### ISSUE THREAD

**Issue by Reinffff** [dickreuter/Poker#99]
Hey there, so i have one interesting problem with Table Setup form.
When i am trying to take screenshot from PS on VDS server (And even without it), its just opens main bot form in a new window and changing table setup window to "Not Responding", so shutting it down  is the only way to close it or do smth with it.
Didnt find anything about it in the wiki, so asking it here.
Also it's gonna be great if u make template for PS (as u do for PP), thank you in advance!

**Comment by dickreuter** [comment]
Looks like a bug, will have a look

**Comment by dickreuter** [comment]
ok it's fixed now.
